name: prj
channels:
  - pytorch
  - nvidia
dependencies:
  - python >= 3.8
  - pytorch >= 1.13
  - torchvision
  - pytorch-cuda=11.7
  - pip 
  - pip:
    - timm
    - diffusers
    - accelerate
    - taming-transformers
    - pytorch-lightning==1.4.2
    - einops==0.3.0
